#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif
#define PLUGIN_VERSION 0,1,3,7
#define IDD_CONFIG                              101
#define IDC_EXTENTWIDTH_EDIT                    1001
#define IDC_EXTENTWIDTH                         1002
#define IDC_EXTENTHEIGHT_EDIT                   1003
#define IDC_EXTENTHEIGHT                        1004
#define IDC_NUMOFLINES_EDIT                     1005
#define IDC_NUMOFLINES                          1006
#define IDC_SCROLLSPEED_EDIT                    1007
#define IDC_SCROLLSPEED                         1008
#define IDC_BACKGROUNDCOLOR                     1009
#define IDC_BACKGROUNDOPACITY_EDIT              1010
#define IDC_BACKGROUNDOPACITY                   1011
#define IDC_POINTFILTERING                      1012
#define IDC_FONT                                1013
#define IDC_TEXTSIZE_EDIT                       1014
#define IDC_TEXTSIZE                            1015
#define IDC_COLOR                               1016
#define IDC_TEXTOPACITY_EDIT                    1017
#define IDC_TEXTOPACITY                         1018
#define IDC_BOLD                                1019
#define IDC_ITALIC                              1020
#define IDC_UNDERLINE                           1021
#define IDC_USEOUTLINE                          1022
#define IDC_OUTLINECOLOR                        1023
#define IDC_OUTLINETHICKNESS_EDIT               1024
#define IDC_OUTLINETHICKNESS                    1025
#define IDC_OUTLINEOPACITY_EDIT                 1026
#define IDC_OUTLINEOPACITY                      1027
#define IDC_USENICKNAME                         1028
#define IDC_NICKNAMEFALLBACKCOLOR               1029
#define IDC_USENICKNAMECOLOR                    1030
#define IDC_NICKNAMEFONT                        1031
#define IDC_NICKNAMESIZE_EDIT                   1032
#define IDC_NICKNAMESIZE                        1033
#define IDC_NICKNAMEBOLD                        1034
#define IDC_NICKNAMEITALIC                      1035
#define IDC_NICKNAMEUNDERLINE                   1036
#define IDC_NICKNAMEUSEOUTLINE                  1037
#define IDC_NICKNAMEOPACITY_EDIT                1038
#define IDC_NICKNAMEOPACITY                     1039
#define IDC_NICKNAMEOUTLINEAUTOCOLOR            1040
#define IDC_NICKNAMEOUTLINECOLOR                1041
#define IDC_NICKNAMEOUTLINETHICKNESS_EDIT       1042
#define IDC_NICKNAMEOUTLINETHICKNESS            1043
#define IDC_NICKNAMEOUTLINEOPACITY_EDIT         1044
#define IDC_NICKNAMEOUTLINEOPACITY              1045
#define IDC_IRCSERVER                           1046
#define IDC_PORT                                1047
#define IDC_CHANNEL                             1048
#define IDC_USEJUSTINFAN                        1049
#define IDC_NICKNAME                            1050
#define IDC_PASSWORD                            1051
